"""add alert monitoring tables

Revision ID: 89f7de861893
Revises: f3cf377612a3
Create Date: 2026-08-15 18:26:03.537620
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "89f7de861893"
down_revision: str | None = "f3cf377612a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_tasks",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("market", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("condition", sa.Text(), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("check_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column("one_shot", sa.Boolean(), nullable=False),
        sa.Column("notification_channel", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trigger_count", sa.Integer(), nullable=False),
        sa.Column("consecutive_errors", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition in ('price_above', 'price_below')",
            name="alert_tasks_condition_check",
        ),
        sa.CheckConstraint(
            "market in ('spot', 'usdm', 'coinm', 'options')",
            name="alert_tasks_market_check",
        ),
        sa.CheckConstraint(
            "notification_channel in ('site', 'feishu')",
            name="alert_tasks_notification_channel_check",
        ),
        sa.CheckConstraint(
            "status in ('active', 'paused', 'completed', 'failed')",
            name="alert_tasks_status_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "alert_tasks_active_due_idx",
        "alert_tasks",
        ["next_check_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "alert_tasks_owner_status_created_idx",
        "alert_tasks",
        ["owner_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "alert_checks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("task_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("observed_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["alert_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "alert_checks_task_created_idx",
        "alert_checks",
        ["task_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "alert_triggers",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("task_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("observed_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("notification_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["alert_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "alert_triggers_task_created_idx",
        "alert_triggers",
        ["task_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "alert_triggers_unnotified_idx",
        "alert_triggers",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("notified = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "alert_triggers_unnotified_idx",
        table_name="alert_triggers",
        postgresql_where=sa.text("notified = false"),
    )
    op.drop_index("alert_triggers_task_created_idx", table_name="alert_triggers")
    op.drop_table("alert_triggers")
    op.drop_index("alert_checks_task_created_idx", table_name="alert_checks")
    op.drop_table("alert_checks")
    op.drop_index("alert_tasks_owner_status_created_idx", table_name="alert_tasks")
    op.drop_index(
        "alert_tasks_active_due_idx",
        table_name="alert_tasks",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("alert_tasks")
    # ### end Alembic commands ###
