"""add trading plan, simulated order and trade review tables

Revision ID: a1b2c3d4e5f6
Revises: c4d5e6f7a8b9
Create Date: 2026-08-15 19:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "c4d5e6f7a8b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trading_plans",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("market", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("entry_low", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("entry_high", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("take_profit", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("position_size", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("risk_note", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "market in ('spot', 'usdm', 'coinm', 'options')",
            name="trading_plans_market_check",
        ),
        sa.CheckConstraint(
            "side in ('long', 'short')",
            name="trading_plans_side_check",
        ),
        sa.CheckConstraint(
            "status in ('planned', 'executed', 'cancelled')",
            name="trading_plans_status_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "trading_plans_owner_created_idx",
        "trading_plans",
        ["owner_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "simulated_orders",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("market", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("order_type", sa.Text(), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("plan_id", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("filled_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "market in ('spot', 'usdm', 'coinm', 'options')",
            name="simulated_orders_market_check",
        ),
        sa.CheckConstraint(
            "side in ('long', 'short')",
            name="simulated_orders_side_check",
        ),
        sa.CheckConstraint(
            "order_type in ('market', 'limit')",
            name="simulated_orders_order_type_check",
        ),
        sa.CheckConstraint(
            "status in ('filled', 'cancelled')",
            name="simulated_orders_status_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "simulated_orders_owner_created_idx",
        "simulated_orders",
        ["owner_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "trade_reviews",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("market", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("entry_reason", sa.Text(), nullable=False),
        sa.Column("outcome_notes", sa.Text(), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "market in ('spot', 'usdm', 'coinm', 'options')",
            name="trade_reviews_market_check",
        ),
        sa.CheckConstraint(
            "side in ('long', 'short')",
            name="trade_reviews_side_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "trade_reviews_owner_created_idx",
        "trade_reviews",
        ["owner_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("trade_reviews_owner_created_idx", table_name="trade_reviews")
    op.drop_table("trade_reviews")
    op.drop_index("simulated_orders_owner_created_idx", table_name="simulated_orders")
    op.drop_table("simulated_orders")
    op.drop_index("trading_plans_owner_created_idx", table_name="trading_plans")
    op.drop_table("trading_plans")
    # ### end Alembic commands ###
