"""add positions table

Revision ID: c4d5e6f7a8b9
Revises: d99045b3fa65
Create Date: 2026-08-15 18:45:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c4d5e6f7a8b9"
down_revision: str | None = "d99045b3fa65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("market", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("leverage", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "market in ('spot', 'usdm', 'coinm', 'options')",
            name="positions_market_check",
        ),
        sa.CheckConstraint(
            "side in ('long', 'short')",
            name="positions_side_check",
        ),
        sa.CheckConstraint(
            "source in ('manual', 'binance')",
            name="positions_source_check",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id",
            "market",
            "symbol",
            "side",
            name="positions_owner_market_symbol_side_key",
        ),
    )
    op.create_index(
        "positions_owner_opened_idx",
        "positions",
        ["owner_id", "opened_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("positions_owner_opened_idx", table_name="positions")
    op.drop_table("positions")
    # ### end Alembic commands ###
