"""add conversation summaries

Revision ID: d99045b3fa65
Revises: 89f7de861893
Create Date: 2026-08-15 18:40:37.679247
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd99045b3fa65'
down_revision: Union[str, None] = '89f7de861893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('summary_through_message_id', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary_through_message_id')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
