"""create agent persistence tables

Revision ID: f3cf377612a3
Revises:
Create Date: 2026-08-15 18:09:25.847832
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f3cf377612a3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("run_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status in ('running', 'paused', 'completed', 'failed')",
            name="agent_runs_status_check",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        "agent_runs_session_status_started_idx",
        "agent_runs",
        ["session_id", "status", "started_at"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role in ('system', 'user', 'assistant', 'tool')",
            name="messages_role_check",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "messages_session_id_id_idx", "messages", ["session_id", "id"], unique=False
    )
    op.create_table(
        "agent_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sequence", name="agent_events_run_sequence_key"),
    )
    op.create_index(
        "agent_events_run_id_sequence_idx",
        "agent_events",
        ["run_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "confirmation_tickets",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("run_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("tool_call", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("permission", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "permission in ('simulate', 'trade')",
            name="confirmation_tickets_permission_check",
        ),
        sa.CheckConstraint(
            "status in ('pending', 'approved', 'denied', 'consumed')",
            name="confirmation_tickets_status_check",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "confirmation_tickets_pending_expires_idx",
        "confirmation_tickets",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "confirmation_tickets_run_id_idx",
        "confirmation_tickets",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "agent_checkpoints",
        sa.Column("confirmation_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("run_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("messages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "pending_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["confirmation_id"], ["confirmation_tickets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("confirmation_id"),
    )
    op.create_index(
        "agent_checkpoints_run_id_idx", "agent_checkpoints", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("agent_checkpoints_run_id_idx", table_name="agent_checkpoints")
    op.drop_table("agent_checkpoints")
    op.drop_index("confirmation_tickets_run_id_idx", table_name="confirmation_tickets")
    op.drop_index(
        "confirmation_tickets_pending_expires_idx",
        table_name="confirmation_tickets",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("confirmation_tickets")
    op.drop_index("agent_events_run_id_sequence_idx", table_name="agent_events")
    op.drop_table("agent_events")
    op.drop_index("messages_session_id_id_idx", table_name="messages")
    op.drop_table("messages")
    op.drop_index("agent_runs_session_status_started_idx", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("conversations")
    # ### end Alembic commands ###
